// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelTimer():Promise<void>;

export function StartTimer(arg1:string,arg2:number,arg3:string):Promise<string>;
